export const GET_INDEX_DATA = "GET_INDEX_DATA";
export const GET_CATS_DATA = "GET_CATS_DATA";
export const GET_CATPRODUCTS_DATA = "GET_CATPRODUCTS_DATA";
export const GET_BESTSELLER_DATA = "GET_BESTSELLER_DATA";
export const GET_LATEST_DATA = "GET_LATEST_DATA";
export const GET_MOSTVIEWED_DATA = "GET_MOSTVIEWED_DATA";

